Repository academydistrict20/notifications, pull requests merged in 2020-07, with the labels that each got.

#115 Docs/typo
  docs/embed/README.md
Labels: prerelease

#116 docs(ui): update style descriptions
  docs/ui/README.md
Labels: release

#119 fix(ui): fix case on wc attribute
  packages/embed/package-lock.json
  packages/embed/src/components/Asd20NotificationsEmbed.vue
Labels: prerelease, release

#122 fix(ui): ssr compatible build
  packages/ui/rollup.config.js
Labels: release
